name: Build

on:
  push:
    branches:
     - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: Build
        run: |
          echo "CONFIG_TARGET_amlogic=y" >> .config
          echo "CONFIG_TARGET_amlogic_s805=y" >> .config
          echo "CONFIG_TARGET_ROOTFS_PARTSIZE=700" >> .config
          echo "CONFIG_TARGET_ROOTFS_EXT4FS=y" >> .config
          echo "CONFIG_LUCI_LANG_zh_Hans=y" >> .config
          echo "CONFIG_TARGET_ROOTFS_PERSIST_VAR=y" >> .config
          echo "CONFIG_HTOP_LMSENSORS=y" >> .config

          echo "CONFIG_FFMPEG_CUSTOM_GPL=y
          CONFIG_FFMPEG_CUSTOM_GPLV3=y
          CONFIG_FFMPEG_CUSTOM_NONFREE=y
          CONFIG_FFMPEG_CUSTOM_PATENTED=y
          CONFIG_FFMPEG_CUSTOM_LARGE=y
          CONFIG_FFMPEG_CUSTOM_MINIDLNA_SUPPORT=y
          CONFIG_FFMPEG_CUSTOM_AUDIO_DEC_SUPPORT=y
          CONFIG_FFMPEG_CUSTOM_PROGRAMS=y
          CONFIG_FFMPEG_CUSTOM_SELECT_libfdk-aac=y
          CONFIG_FFMPEG_CUSTOM_SELECT_libmp3lame=y
          CONFIG_FFMPEG_CUSTOM_SELECT_libopus=y
          CONFIG_FFMPEG_CUSTOM_SELECT_libshine=y
          CONFIG_FFMPEG_CUSTOM_ENCODER_ac3=y
          CONFIG_FFMPEG_CUSTOM_ENCODER_jpegls=y
          CONFIG_FFMPEG_CUSTOM_ENCODER_mpeg1video=y
          CONFIG_FFMPEG_CUSTOM_ENCODER_mpeg2video=y
          CONFIG_FFMPEG_CUSTOM_ENCODER_mpeg4=y
          CONFIG_FFMPEG_CUSTOM_ENCODER_pcm_s16be=y
          CONFIG_FFMPEG_CUSTOM_ENCODER_pcm_s16le=y
          CONFIG_FFMPEG_CUSTOM_ENCODER_png=y
          CONFIG_FFMPEG_CUSTOM_ENCODER_vorbis=y
          CONFIG_FFMPEG_CUSTOM_ENCODER_zlib=y
          CONFIG_FFMPEG_CUSTOM_DECODER_aac=y
          CONFIG_FFMPEG_CUSTOM_SELECT_adpcm=y
          CONFIG_FFMPEG_CUSTOM_DECODER_ac3=y
          CONFIG_FFMPEG_CUSTOM_DECODER_alac=y
          CONFIG_FFMPEG_CUSTOM_DECODER_amrnb=y
          CONFIG_FFMPEG_CUSTOM_DECODER_amrwb=y
          CONFIG_FFMPEG_CUSTOM_DECODER_ape=y
          CONFIG_FFMPEG_CUSTOM_DECODER_atrac3=y
          CONFIG_FFMPEG_CUSTOM_DECODER_flac=y
          CONFIG_FFMPEG_CUSTOM_DECODER_gif=y
          CONFIG_FFMPEG_CUSTOM_DECODER_h264=y
          CONFIG_FFMPEG_CUSTOM_DECODER_hevc=y
          CONFIG_FFMPEG_CUSTOM_DECODER_jpegls=y
          CONFIG_FFMPEG_CUSTOM_DECODER_mp2=y
          CONFIG_FFMPEG_CUSTOM_DECODER_mp3=y
          CONFIG_FFMPEG_CUSTOM_DECODER_mpegvideo=y
          CONFIG_FFMPEG_CUSTOM_DECODER_mpeg1video=y
          CONFIG_FFMPEG_CUSTOM_DECODER_mpeg2video=y
          CONFIG_FFMPEG_CUSTOM_DECODER_mpeg4=y
          CONFIG_FFMPEG_CUSTOM_DECODER_mpc7=y
          CONFIG_FFMPEG_CUSTOM_DECODER_mpc8=y
          CONFIG_FFMPEG_CUSTOM_DECODER_opus=y
          CONFIG_FFMPEG_CUSTOM_DECODER_pcm_s16be=y
          CONFIG_FFMPEG_CUSTOM_DECODER_pcm_s16le=y
          CONFIG_FFMPEG_CUSTOM_DECODER_png=y
          CONFIG_FFMPEG_CUSTOM_DECODER_vc1=y
          CONFIG_FFMPEG_CUSTOM_DECODER_vorbis=y
          CONFIG_FFMPEG_CUSTOM_DECODER_wavpack=y
          CONFIG_FFMPEG_CUSTOM_DECODER_wmav1=y
          CONFIG_FFMPEG_CUSTOM_DECODER_wmav2=y
          CONFIG_FFMPEG_CUSTOM_DECODER_zlib=y
          CONFIG_FFMPEG_CUSTOM_MUXER_ac3=y
          CONFIG_FFMPEG_CUSTOM_MUXER_avi=y
          CONFIG_FFMPEG_CUSTOM_MUXER_h264=y
          CONFIG_FFMPEG_CUSTOM_MUXER_hevc=y
          CONFIG_FFMPEG_CUSTOM_MUXER_mp3=y
          CONFIG_FFMPEG_CUSTOM_MUXER_mp4=y
          CONFIG_FFMPEG_CUSTOM_MUXER_mpeg1video=y
          CONFIG_FFMPEG_CUSTOM_MUXER_mpeg2video=y
          CONFIG_FFMPEG_CUSTOM_MUXER_mpegts=y
          CONFIG_FFMPEG_CUSTOM_MUXER_ogg=y
          CONFIG_FFMPEG_CUSTOM_MUXER_rtp=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_aac=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_avi=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_ac3=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_amr=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_ape=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_flac=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_h264=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_hevc=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_matroska=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_mov=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_mp3=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_mpegvideo=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_mpegps=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_mpegts=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_mpc=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_mpc8=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_ogg=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_rm=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_rtsp=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_sdp=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_rtp=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_vc1=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_wav=y
          CONFIG_FFMPEG_CUSTOM_DEMUXER_wv=y
          CONFIG_FFMPEG_CUSTOM_PARSER_aac=y
          CONFIG_FFMPEG_CUSTOM_PARSER_flac=y
          CONFIG_FFMPEG_CUSTOM_PARSER_h264=y
          CONFIG_FFMPEG_CUSTOM_PARSER_hevc=y
          CONFIG_FFMPEG_CUSTOM_PARSER_mpegaudio=y
          CONFIG_FFMPEG_CUSTOM_PARSER_mpegvideo=y
          CONFIG_FFMPEG_CUSTOM_PARSER_mpeg4video=y
          CONFIG_FFMPEG_CUSTOM_PARSER_opus=y
          CONFIG_FFMPEG_CUSTOM_PARSER_vc1=y
          CONFIG_FFMPEG_CUSTOM_PROTOCOL_file=y
          CONFIG_FFMPEG_CUSTOM_PROTOCOL_http=y
          CONFIG_FFMPEG_CUSTOM_PROTOCOL_icecast=y
          CONFIG_FFMPEG_CUSTOM_PROTOCOL_pipe=y
          CONFIG_FFMPEG_CUSTOM_PROTOCOL_rtp=y
          CONFIG_FFMPEG_CUSTOM_PROTOCOL_tcp=y
          CONFIG_FFMPEG_CUSTOM_PROTOCOL_udp=y
          " >> .config
          make defconfig
          make -j$(nproc)


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            bin/targets/amlogic/s805/openwrt-amlogic-s805-onecloud-ext4-combined.*

      - name: Create or update release and upload assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/targets/amlogic/s805/openwrt-amlogic-s805-onecloud-ext4-combined.*
          tag_name: ${{ env.TAG_NAME }}
          name: "openwrt-amlogic-s805-onecloud-ext4-combined-${{ env.TAG_NAME }}.bin.gz"
          body: |
            This is a release with multiple uploaded assets.
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
