name: Build

on:
  push:
    branches:
     - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: Build
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp onecloud.config .config
          make defconfig
          make -j$(nproc)


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            bin/targets/amlogic/s805/openwrt-amlogic-s805-onecloud-ext4-combined.bin.gz

      - name: Create or update release and upload artifact
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/targets/amlogic/s805/openwrt-amlogic-s805-onecloud-ext4-combined.bin.gz
          tag_name: ${{ env.TAG_NAME }}
          name: "openwrt-amlogic-s805-onecloud-ext4-combined-${{ env.TAG_NAME }}.bin.gz"
          body: |
            This is a release with multiple uploaded assets.
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
